apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: l42s22mdk-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:7346e31f27e60896768e65001e3f78f8391c1b2f@sha256:8158d31fd504f10cbb452397eea1929f04c6d1d23f83bd42386f6e6a3552695f
          name: container-image
